version: '3.4'

services:
  exercise.wwwapi:
    image: ${DOCKER_REGISTRY-}exercisewwwapi
    build:
      context: .
      dockerfile: exercise.wwwapi/Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"
