version: '3.4'

services:
  workshop.wwwapi:
    image: ${DOCKER_REGISTRY-}workshopwwwapi
    build:
      context: .
      dockerfile: workshop.wwwapi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - sibbs-network
    depends_on:
      workshop.database:
        condition: service_healthy
  workshop.database:
    container_name: 'workshop.database'
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
        - './.containers/cars-data:/var/lib/postgresql/data'
    ports:
        - 5432:5432
    networks:
      - sibbs-network
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
networks:
  sibbs-network:
    driver: bridge